### ISSUE TITLE
Submodules content

### ISSUE THREAD

**Issue by jcolomb** [G-Node/tonic#20]
Creation of submodules:
- A default template:
    - with a synchronisation script
    - with a git annex rules document in .gitattributes
- issue and wiki redirected

Anything else?

**Comment by achilleas-k** [comment]
Need to make sure the project creation service handles submodules properly.

**Comment by jcolomb** [comment]
submodule template at https://gin.g-node.org/gin4RRI/Template_Submodule_default

(for some reason it used git annex at some point, maybe for the scripts)?

**Comment by jcolomb** [comment]
submodule template at https://gin.g-node.org/gin4RRI/Template_Submodule_default

(for some reason it used git annex at some point, maybe for the scripts)?
