### ISSUE TITLE
docker looking for test bot

### ISSUE THREAD

**Issue by jcolomb** [G-Node/tonic#21]
trying to run via docker and got this error. is testbot missing ?
```
OPY testbot /tonic/testbot
COPY failed: stat /var/lib/docker/tmp/docker-builder001710620/testbot: no such file or directory
```

**Comment by achilleas-k** [comment]
The `testbot` file was originally the file containing the username and password for the bot/service user.  I removed it since now every service should define its own credentials (and general configuration) separately.  I'll update the Dockerfile to not look for this.

**Comment by achilleas-k** [comment]
This is now fixed and documentation about how to set up and configure the service is being added in PR #29.
