### ISSUE TITLE
submodule title

### ISSUE THREAD

**Issue by jcolomb** [G-Node/tonic#31]
`Title: A title for the project.
The project title is added to the repository's Description/Title field on GIN.`

Will the title be used in the description of the submodules repository ? It would be nice (manuscript for `Title`),
one could also add the url of the parent repository on the same step, so that one could go from submodules to parent, at least manually.

**Comment by achilleas-k** [comment]
Yes, I thought that might be a way to use it as well.  The title is copied to the submodules as is now, but I was thinking it might become "Project title (code directory)", but I like your idea of "Code for Project title" better.

Adding the title to the README is also a good idea.  Would this conflict (or have to include) any other information you would want to have the in the README coming from the template?

**Comment by jcolomb** [comment]
this is done in the script for now, as tonic doesnot set the submodules yet.

**Comment by jcolomb** [comment]
done with new version
